### Importing packages and data

In [2]:
import pandas as pd
import math
import statistics
import copy
import datetime

In [204]:
regular = pd.read_csv("/Users/Tim/Downloads/regular.csv")
regular2 = pd.read_csv("/Users/Tim/Downloads/regular2.csv")

In [205]:
playoffs = pd.read_csv("/Users/Tim/Downloads/playoffs.csv")
playoffs2 = pd.read_csv("/Users/Tim/Downloads/playoffs2.csv")

In [206]:
usage = pd.read_csv("/Users/Tim/Downloads/usage.csv")
usg_allstar = pd.read_csv("/Users/Tim/Downloads/usg_allstar.csv")

### Joining regular season and playoff games into 1 dataset

In [207]:
regP = []
for i in range(len(regular)):
    regP.append(0)
    
playP = []
for i in range(len(playoffs)):
    playP.append(1)

In [208]:
regular["PLAYOFF_IND"] = regP

playoffs["PLAYOFF_IND"] = playP

In [209]:
alldata = pd.concat([regular, playoffs]).reset_index(drop=True)

In [210]:
alldata

,Unnamed: 0,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE,MATCHUP,WL,MIN_x,...,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,PLAYOFF_IND
0,0,22017,1610612759,SAS,San Antonio Spurs,21701226,2018-04-11,SAS @ NOP,L,241,...,0.446,0.488,1.0,0.198,104.86,105.00,87.50,105,0.348,0
1,1,22017,1610612739,CLE,Cleveland Cavaliers,21701220,2018-04-11,CLE vs. NYK,L,241,...,0.426,0.461,1.0,0.196,101.52,97.00,80.83,96,0.379,0
2,2,22017,1610612758,SAC,Sacramento Kings,21701230,2018-04-11,SAC vs. HOU,W,240,...,0.519,0.541,1.0,0.200,93.54,92.00,76.67,92,0.697,0
3,3,22017,1610612762,UTA,Utah Jazz,21701229,2018-04-11,UTA @ POR,L,241,...,0.416,0.467,1.0,0.197,99.80,97.50,81.25,97,0.434,0
4,4,22017,1610612761,TOR,Toronto Raptors,21701221,2018-04-11,TOR @ MIA,L,265,...,0.505,0.538,1.0,0.198,95.57,94.19,78.49,105,0.466,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15085,967,42022,1610612739,CLE,Cleveland Cavaliers,42200131,2023-04-15,CLE vs. NYK,L,241,...,0.494,0.526,1.0,0.201,95.96,95.00,79.17,95,0.476,1
15086,968,42022,1610612744,GSW,Golden State Warriors,42200161,2023-04-15,GSW @ SAC,L,239,...,0.567,0.604,1.0,0.202,107.98,105.50,87.92,106,0.517,1
15087,969,42022,1610612738,BOS,Boston Celtics,42200111,2023-04-15,BOS vs. ATL,W,240,...,0.551,0.584,1.0,0.198,102.80,103.50,86.25,104,0.586,1
15088,970,42022,1610612758,SAC,Sacramento Kings,42200161,2023-04-15,SAC vs. GSW,W,240,...,0.510,0.562,1.0,0.203,107.98,105.50,87.92,105,0.483,1
15089,971,42022,1610612737,ATL,Atlanta Hawks,42200111,2023-04-15,ATL @ BOS,L,241,...,0.413,0.460,1.0,0.201,102.80,103.50,86.25,103,0.414,1

### Dropping columns that aren't needed, and putting data in chronological order

In [165]:
alldata.columns

Index(['Unnamed: 0', 'SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION_x',
       'TEAM_NAME_x', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN_x', 'PTS',
       'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA',
       'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PLUS_MINUS', 'TEAM_NAME_y', 'TEAM_ABBREVIATION_y', 'TEAM_CITY',
       'MIN_y', 'E_OFF_RATING', 'OFF_RATING', 'E_DEF_RATING', 'DEF_RATING',
       'E_NET_RATING', 'NET_RATING', 'AST_PCT', 'AST_TOV', 'AST_RATIO',
       'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'E_TM_TOV_PCT', 'TM_TOV_PCT',
       'EFG_PCT', 'TS_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE', 'PACE',
       'PACE_PER40', 'POSS', 'PIE', 'PLAYOFF_IND'],
      dtype='object')

In [211]:
alldata = alldata.drop(columns=['Unnamed: 0', 'TEAM_NAME_y', 'TEAM_ABBREVIATION_y','TEAM_CITY',
       'MIN_y','E_OFF_RATING', 'E_DEF_RATING', 'E_NET_RATING', 'E_TM_TOV_PCT', 'USG_PCT', 'E_USG_PCT', 'E_PACE'])

In [212]:
alldata = alldata.rename(columns={"TEAM_ABBREVIATION_x": "TEAM_ABBREVIATION", "TEAM_NAME_x": "TEAM_NAME", "MIN_x": "MIN"})

In [213]:
alldata = alldata.sort_values(by='GAME_DATE').reset_index(drop=True)

### Getting DNP players, and making column for game number

In [214]:
## Counting how many key players did not play for a team in each game

dnp = usage[usage['COMMENT'].notna()].reset_index(drop=True)

key_ids = usg_allstar['PLAYER_ID'].unique()

key_dnp = {}

for i in range(len(dnp)):
    if dnp['PLAYER_ID'][i] in key_ids:
        if (dnp['GAME_ID'][i], dnp['TEAM_ID'][i]) in key_dnp:
            key_dnp[(dnp['GAME_ID'][i], dnp['TEAM_ID'][i])] += 1
        else:
            key_dnp[(dnp['GAME_ID'][i], dnp['TEAM_ID'][i])] = 1

In [215]:
## Assigning values based on team and game id for key DNP players

alldata["KEY_DNP"] = 0

for i in range(len(alldata)):
    if (alldata["GAME_ID"][i], alldata['TEAM_ID'][i]) in key_dnp:
        alldata['KEY_DNP'][i] = key_dnp[(alldata["GAME_ID"][i], alldata['TEAM_ID'][i])]

/var/folders/01/bfdvy8nx5pj47db665p5yndm0000gn/T/ipykernel_2051/1776894652.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alldata['KEY_DNP'][i] = key_dnp[(alldata["GAME_ID"][i], alldata['TEAM_ID'][i])]

In [216]:
## Making dictionary to keep track of game count
abr = list(alldata.TEAM_ABBREVIATION.unique())
team_game_count = {}

for ab in abr:
    team_game_count[ab] = 1

season = alldata['SEASON_ID'][0]

In [217]:
## Creating game count
alldata["GAME_NUMBER"] = 0

for i in range(len(alldata)):
    if alldata['SEASON_ID'][i] != season and alldata['PLAYOFF_IND'][i] !=1:
        season = alldata['SEASON_ID'][i]
        for ab in abr:
            team_game_count[ab] = 1
    alldata['GAME_NUMBER'][i] = team_game_count[alldata['TEAM_ABBREVIATION'][i]]
    team_game_count[alldata['TEAM_ABBREVIATION'][i]] += 1

/var/folders/01/bfdvy8nx5pj47db665p5yndm0000gn/T/ipykernel_2051/3337852170.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  alldata['GAME_NUMBER'][i] = team_game_count[alldata['TEAM_ABBREVIATION'][i]]

In [173]:
alldata.to_csv('alldata.csv')

### Getting opponent stats for each team
So when getting data from previous games we can get the avg opponent stats

In [280]:
## Self joining and filtering to where it is the stats for 2 different teams

opp = copy.deepcopy(alldata)

In [194]:
alldata_total = pd.merge(alldata, opp, how="inner", left_on=['GAME_ID'], right_on = ['GAME_ID'])

In [195]:
alldata_total = alldata_total[alldata_total['TEAM_NAME_x'] != alldata_total['TEAM_NAME_y']].reset_index(drop=True)

In [196]:
alldata_total.columns

Index(['SEASON_ID_x', 'TEAM_ID_x', 'TEAM_ABBREVIATION_x', 'TEAM_NAME_x',
       'GAME_ID', 'GAME_DATE_x', 'MATCHUP_x', 'WL_x', 'MIN_x', 'PTS_x',
       'FGM_x', 'FGA_x', 'FG_PCT_x', 'FG3M_x', 'FG3A_x', 'FG3_PCT_x', 'FTM_x',
       'FTA_x', 'FT_PCT_x', 'OREB_x', 'DREB_x', 'REB_x', 'AST_x', 'STL_x',
       'BLK_x', 'TOV_x', 'PF_x', 'PLUS_MINUS_x', 'OFF_RATING_x',
       'DEF_RATING_x', 'NET_RATING_x', 'AST_PCT_x', 'AST_TOV_x', 'AST_RATIO_x',
       'OREB_PCT_x', 'DREB_PCT_x', 'REB_PCT_x', 'TM_TOV_PCT_x', 'EFG_PCT_x',
       'TS_PCT_x', 'PACE_x', 'PACE_PER40_x', 'POSS_x', 'PIE_x',
       'PLAYOFF_IND_x', 'KEY_DNP_x', 'GAME_NUMBER_x', 'SEASON_ID_y',
       'TEAM_ID_y', 'TEAM_ABBREVIATION_y', 'TEAM_NAME_y', 'GAME_DATE_y',
       'MATCHUP_y', 'WL_y', 'MIN_y', 'PTS_y', 'FGM_y', 'FGA_y', 'FG_PCT_y',
       'FG3M_y', 'FG3A_y', 'FG3_PCT_y', 'FTM_y', 'FTA_y', 'FT_PCT_y', 'OREB_y',
       'DREB_y', 'REB_y', 'AST_y', 'STL_y', 'BLK_y', 'TOV_y', 'PF_y',
       'PLUS_MINUS_y', 'OFF_RATING_y', 'DEF_RATING_y', 'NET_RATING_y',
       'AST_PCT_y', 'AST_TOV_y', 'AST_RATIO_y', 'OREB_PCT_y', 'DREB_PCT_y',
       'REB_PCT_y', 'TM_TOV_PCT_y', 'EFG_PCT_y', 'TS_PCT_y', 'PACE_y',
       'PACE_PER40_y', 'POSS_y', 'PIE_y', 'PLAYOFF_IND_y', 'KEY_DNP_y',
       'GAME_NUMBER_y'],
      dtype='object')

In [197]:
## Dropping columns not relevent to the team, and changing column names
alldata_total = alldata_total.drop(columns=['SEASON_ID_y', 'TEAM_ID_y',
       'TEAM_ABBREVIATION_y', 'TEAM_NAME_y', 'GAME_DATE_y', 'MATCHUP_y',
       'WL_y', 'MIN_y', 'FGM_y', 'FGA_y', 'FTM_y', 'FT_PCT_y', 'AST_y',
       'PLUS_MINUS_y','AST_PCT_y', 'AST_TOV_y', 'AST_RATIO_y','PACE_y', 'PACE_PER40_y','POSS_y','PLAYOFF_IND_y'])

In [198]:
colnames = list(alldata_total.columns)

newname = {}

for name in colnames:
    if name[-2:] == "_x":
        newname[name] = name[:-2]
    if name[-2:] == "_y":
        newname[name] = name[:-2] + "_opp"

In [199]:
alldata_total = alldata_total.rename(columns=newname)
alldata_total= alldata_total.sort_values(by='GAME_DATE').reset_index(drop=True)

### Creating home team indicator column, and changing W/L to 1s and 0s, and creating new column for win percentage

In [200]:
home = []

for i in range(len(alldata_total)):
    if alldata_total['MATCHUP'][i][4] == "v":
        home.append(1)
    else:
        home.append(0)
        
alldata_total["HOME"] = home

win = []

for i in range(len(alldata_total)):
    if alldata_total['WL'][i] == "W":
        win.append(1)
    else:
        win.append(0)

alldata_total['WL'] = win

alldata_total["WIN_PERC"] = alldata_total['WL']

### Creating columns for rest time, and indicator for playing a back to back

In [272]:
## Back to back

back2back = []
rest = []
abr = list(alldata_total.TEAM_ABBREVIATION.unique())
dates = {}

for team in abr:
    dates[team] = datetime.datetime.strptime('2016-01-01', "%Y-%m-%d")
    
for i in range(len(alldata_total)):
    
    if alldata_total['GAME_NUMBER'][i] == 1:
        rest.append(5)
        dates[alldata_total['TEAM_ABBREVIATION'][i]] = datetime.datetime.strptime(alldata_total['GAME_DATE'][i], "%Y-%m-%d")
        back2back.append(0)
    else:
        diff = (datetime.datetime.strptime(alldata_total['GAME_DATE'][i], "%Y-%m-%d") - dates[alldata_total['TEAM_ABBREVIATION'][i]]).days
        if diff == 0:
            print(datetime.datetime.strptime(alldata_total['GAME_DATE'][i], "%Y-%m-%d"))
            print(dates[alldata_total['TEAM_ABBREVIATION'][i]])
            print(i)
            break 
        if diff == 1:
            back2back.append(1)
        else:
            back2back.append(0)
        rest.append(diff)
        dates[alldata_total['TEAM_ABBREVIATION'][i]] = datetime.datetime.strptime(alldata_total['GAME_DATE'][i], "%Y-%m-%d")

In [274]:
alldata_total['BACK_BACK'] = back2back
alldata_total['REST'] = rest

In [279]:
alldata_total.to_csv("alldata_total.csv")

### Creating variable for number of games played in previous 7 days

In [7]:
alldata_total = pd.read_csv('/Users/Tim/Downloads/alldata_total.csv')
alldata_total = alldata_total.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

In [11]:
games_played = []
abr = list(alldata_total.TEAM_ABBREVIATION.unique())



for i in range(len(alldata_total)):
    
    team = alldata_total['TEAM_ABBREVIATION'][i]
    
    if alldata_total['GAME_NUMBER'][i] == 1:
        games_played.append(0)
    else:
        date = datetime.datetime.strptime(alldata_total['GAME_DATE'][i], "%Y-%m-%d")
        back = 0
        count = 0
        while (i-back>=0) and ((date-datetime.datetime.strptime(alldata_total['GAME_DATE'][i-back], "%Y-%m-%d")).days <8):
            if alldata_total['TEAM_ABBREVIATION'][i-back]==team:
                count +=1
            back+=1
        games_played.append(count)

In [15]:
alldata_total["GAMES_PLAYED_7"] = games_played

In [18]:
alldata_total.to_csv("alldata_total.csv")

### Formatting data for the ELO model

In [219]:
elodata = pd.concat([regular2, playoffs2]).reset_index(drop=True)

In [220]:
## Dropping unneccesary columns
elodata = elodata.drop(columns=['Unnamed: 0', 'MIN','FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF'])

elodata = elodata.sort_values(by='GAME_DATE').reset_index(drop=True)

In [221]:
elodata

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,PTS,PLUS_MINUS
0,21990,1610612746,LAC,Los Angeles Clippers,29000008,1990-11-02,LAC vs. SAC,W,90,NaN
1,21990,1610612751,NJN,New Jersey Nets,29000004,1990-11-02,NJN @ IND,L,81,NaN
2,21990,1610612752,NYK,New York Knicks,29000003,1990-11-02,NYK @ CHH,W,134,NaN
3,21990,1610612738,BOS,Boston Celtics,29000012,1990-11-02,BOS vs. CLE,W,125,NaN
4,21990,1610612758,SAC,Sacramento Kings,29000008,1990-11-02,SAC @ LAC,L,80,NaN
...,...,...,...,...,...,...,...,...,...,...
67279,42016,1610612744,GSW,Golden State Warriors,41600403,2017-06-07,GSW @ CLE,W,118,5.0
67280,42016,1610612739,CLE,Cleveland Cavaliers,41600404,2017-06-09,CLE vs. GSW,W,137,19.0
67281,42016,1610612744,GSW,Golden State Warriors,41600404,2017-06-09,GSW @ CLE,L,116,-19.0
67282,42016,1610612744,GSW,Golden State Warriors,41600405,2017-06-12,GSW vs. CLE,W,129,9.0
67283,42016,1610612739,CLE,Cleveland Cavaliers,41600405,2017-06-12,CLE @ GSW,L,120,-9.0

In [222]:
## Making home team indicator column and changing win loss to 1s and 0s
home = []
wins = []

for i in range(len(elodata)):
    if elodata['MATCHUP'][i][4] == "v":
        home.append(1)
    else:
        home.append(0)
    
    if elodata['WL'][i] == 'W':
        wins.append(1)
    else:
        wins.append(0)
    
        
elodata["HOME"] = home
elodata['WL'] = wins

In [223]:
## Renaming teams that had their name changed
eloABR = list(elodata.TEAM_ABBREVIATION.unique())
eloTeam = list(elodata.TEAM_NAME.unique())

for i in eloABR:
    if i not in abr:
        print(i)
        
for i in eloTeam:
    if i not in teams:
        print(i)

NJN
PHL
UTH
GOS
CHH
SEA
SAN
VAN
NOH
NOK
Los Angeles Clippers
New Jersey Nets
Washington Bullets
Seattle SuperSonics
Vancouver Grizzlies
New Orleans Hornets
Charlotte Bobcats
New Orleans/Oklahoma City Hornets

In [224]:
for i in range(len(elodata)):
    
    if elodata.loc[i,"TEAM_ABBREVIATION"] == 'NJN':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'BKN'
    elif elodata["TEAM_ABBREVIATION"][i] == 'PHL':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'PHI'
    elif elodata["TEAM_ABBREVIATION"][i] == 'UTH':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'UTA'
    elif elodata["TEAM_ABBREVIATION"][i] == 'GOS':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'GSW'
    elif elodata["TEAM_ABBREVIATION"][i] == 'CHH':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'CHA'
    elif elodata["TEAM_ABBREVIATION"][i] == 'SEA':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'OKC'
    elif elodata["TEAM_ABBREVIATION"][i] == 'SAN':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'SAS'
    elif elodata["TEAM_ABBREVIATION"][i] == 'VAN':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'MEM'
    elif elodata["TEAM_ABBREVIATION"][i] == 'NOH':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'NOP'
    elif elodata["TEAM_ABBREVIATION"][i] == 'NOK':
        elodata.loc[i,"TEAM_ABBREVIATION"] = 'NOP'

In [226]:
## Making 1 row per game
elo_hStats = elodata[elodata['HOME'] == 1] 
elo_aStats = elodata[elodata['HOME'] == 0]

In [227]:
elo_reformat = pd.merge(elo_hStats, elo_aStats, how="inner", left_on=['GAME_ID'], right_on = ['GAME_ID'])

elo_reformat = elo_reformat.sort_values(by='GAME_DATE_x').reset_index(drop=True)

In [235]:
elo_reformat

,SEASON_ID_x,TEAM_ID_x,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE_x,MATCHUP_x,WL_x,PTS_x,PLUS_MINUS_x,...,SEASON_ID_y,TEAM_ID_y,TEAM_ABBREVIATION_y,TEAM_NAME_y,GAME_DATE_y,MATCHUP_y,WL_y,PTS_y,PLUS_MINUS_y,HOME_y
0,21990,1610612746,LAC,Los Angeles Clippers,29000008,1990-11-02,LAC vs. SAC,1,90,10.0,...,21990,1610612758,SAC,Sacramento Kings,1990-11-02,SAC @ LAC,0,80,-10.0,0
1,21990,1610612750,MIN,Minnesota Timberwolves,29000007,1990-11-02,MIN vs. DAL,1,98,13.0,...,21990,1610612742,DAL,Dallas Mavericks,1990-11-02,DAL @ MIN,0,85,-13.0,0
2,21990,1610612757,POR,Portland Trail Blazers,29000001,1990-11-02,POR vs. HOU,1,90,1.0,...,21990,1610612745,HOU,Houston Rockets,1990-11-02,HOU @ POR,0,89,-1.0,0
3,21990,1610612743,DEN,Denver Nuggets,29000002,1990-11-02,DEN vs. GOS,0,158,-4.0,...,21990,1610612744,GSW,Golden State Warriors,1990-11-02,GOS @ DEN,1,162,4.0,0
4,21990,1610612741,CHI,Chicago Bulls,29000009,1990-11-02,CHI vs. PHL,0,116,-8.0,...,21990,1610612755,PHI,Philadelphia 76ers,1990-11-02,PHL @ CHI,1,124,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33637,42016,1610612744,GSW,Golden State Warriors,41600401,2017-06-01,GSW vs. CLE,1,113,22.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-01,CLE @ GSW,0,91,-22.0,0
33638,42016,1610612744,GSW,Golden State Warriors,41600402,2017-06-04,GSW vs. CLE,1,132,19.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-04,CLE @ GSW,0,113,-19.0,0
33639,42016,1610612739,CLE,Cleveland Cavaliers,41600403,2017-06-07,CLE vs. GSW,0,113,-5.0,...,42016,1610612744,GSW,Golden State Warriors,2017-06-07,GSW @ CLE,1,118,5.0,0
33640,42016,1610612739,CLE,Cleveland Cavaliers,41600404,2017-06-09,CLE vs. GSW,1,137,19.0,...,42016,1610612744,GSW,Golden State Warriors,2017-06-09,GSW @ CLE,0,116,-19.0,0
33641,42016,1610612744,GSW,Golden State Warriors,41600405,2017-06-12,GSW vs. CLE,1,129,9.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-12,CLE @ GSW,0,120,-9.0,0

In [229]:
## Fixing plus minus values for years before they recorded that stat
for i in range(len(elo_reformat)):
    if math.isnan(elo_reformat['PLUS_MINUS_x'][i]):
        diff = elo_reformat['PTS_x'][i] - elo_reformat['PTS_y'][i]
        
        elo_reformat.loc[i,'PLUS_MINUS_x'] = diff
        elo_reformat.loc[i,'PLUS_MINUS_y'] = -diff

In [230]:
elo_reformat

,SEASON_ID_x,TEAM_ID_x,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE_x,MATCHUP_x,WL_x,PTS_x,PLUS_MINUS_x,...,SEASON_ID_y,TEAM_ID_y,TEAM_ABBREVIATION_y,TEAM_NAME_y,GAME_DATE_y,MATCHUP_y,WL_y,PTS_y,PLUS_MINUS_y,HOME_y
0,21990,1610612746,LAC,Los Angeles Clippers,29000008,1990-11-02,LAC vs. SAC,1,90,10.0,...,21990,1610612758,SAC,Sacramento Kings,1990-11-02,SAC @ LAC,0,80,-10.0,0
1,21990,1610612750,MIN,Minnesota Timberwolves,29000007,1990-11-02,MIN vs. DAL,1,98,13.0,...,21990,1610612742,DAL,Dallas Mavericks,1990-11-02,DAL @ MIN,0,85,-13.0,0
2,21990,1610612757,POR,Portland Trail Blazers,29000001,1990-11-02,POR vs. HOU,1,90,1.0,...,21990,1610612745,HOU,Houston Rockets,1990-11-02,HOU @ POR,0,89,-1.0,0
3,21990,1610612743,DEN,Denver Nuggets,29000002,1990-11-02,DEN vs. GOS,0,158,-4.0,...,21990,1610612744,GSW,Golden State Warriors,1990-11-02,GOS @ DEN,1,162,4.0,0
4,21990,1610612741,CHI,Chicago Bulls,29000009,1990-11-02,CHI vs. PHL,0,116,-8.0,...,21990,1610612755,PHI,Philadelphia 76ers,1990-11-02,PHL @ CHI,1,124,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33637,42016,1610612744,GSW,Golden State Warriors,41600401,2017-06-01,GSW vs. CLE,1,113,22.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-01,CLE @ GSW,0,91,-22.0,0
33638,42016,1610612744,GSW,Golden State Warriors,41600402,2017-06-04,GSW vs. CLE,1,132,19.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-04,CLE @ GSW,0,113,-19.0,0
33639,42016,1610612739,CLE,Cleveland Cavaliers,41600403,2017-06-07,CLE vs. GSW,0,113,-5.0,...,42016,1610612744,GSW,Golden State Warriors,2017-06-07,GSW @ CLE,1,118,5.0,0
33640,42016,1610612739,CLE,Cleveland Cavaliers,41600404,2017-06-09,CLE vs. GSW,1,137,19.0,...,42016,1610612744,GSW,Golden State Warriors,2017-06-09,GSW @ CLE,0,116,-19.0,0
33641,42016,1610612744,GSW,Golden State Warriors,41600405,2017-06-12,GSW vs. CLE,1,129,9.0,...,42016,1610612739,CLE,Cleveland Cavaliers,2017-06-12,CLE @ GSW,0,120,-9.0,0

In [236]:
elo_reformat.columns

Index(['SEASON_ID_x', 'TEAM_ID_x', 'TEAM_ABBREVIATION_x', 'TEAM_NAME_x',
       'GAME_ID', 'GAME_DATE_x', 'MATCHUP_x', 'WL_x', 'PTS_x', 'PLUS_MINUS_x',
       'HOME_x', 'SEASON_ID_y', 'TEAM_ID_y', 'TEAM_ABBREVIATION_y',
       'TEAM_NAME_y', 'GAME_DATE_y', 'MATCHUP_y', 'WL_y', 'PTS_y',
       'PLUS_MINUS_y', 'HOME_y'],
      dtype='object')

In [232]:
## Repeating process for seasons 17-23
alldata

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,TM_TOV_PCT,EFG_PCT,TS_PCT,PACE,PACE_PER40,POSS,PIE,PLAYOFF_IND,KEY_DNP,GAME_NUMBER
0,22017,1610612739,CLE,Cleveland Cavaliers,21700001,2017-10-17,CLE vs. BOS,W,239,102,...,17.3,0.488,0.543,98.5,82.08,98,0.491,0,0,1
1,22017,1610612738,BOS,Boston Celtics,21700001,2017-10-17,BOS @ CLE,L,241,99,...,12.1,0.455,0.500,98.5,82.08,99,0.509,0,0,1
2,22017,1610612744,GSW,Golden State Warriors,21700002,2017-10-17,GSW vs. HOU,L,241,121,...,16.8,0.638,0.678,101.0,84.17,101,0.515,0,0,1
3,22017,1610612745,HOU,Houston Rockets,21700002,2017-10-17,HOU @ GSW,W,239,122,...,12.9,0.562,0.579,101.0,84.17,101,0.485,0,0,1
4,22017,1610612749,MIL,Milwaukee Bucks,21700007,2017-10-18,MIL @ BOS,W,238,108,...,15.0,0.546,0.605,100.5,83.75,100,0.583,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15085,42022,1610612756,PHX,Phoenix Suns,42200226,2023-05-11,PHX vs. DEN,L,243,100,...,14.1,0.551,0.569,98.5,82.08,99,0.357,1,1,93
15086,42022,1610612747,LAL,Los Angeles Lakers,42200236,2023-05-12,LAL vs. GSW,W,240,122,...,7.4,0.607,0.653,95.5,79.58,95,0.667,1,0,94
15087,42022,1610612744,GSW,Golden State Warriors,42200236,2023-05-12,GSW @ LAL,L,241,101,...,11.5,0.442,0.463,95.5,79.58,96,0.333,1,0,95
15088,42022,1610612748,MIA,Miami Heat,42200206,2023-05-12,MIA vs. NYK,W,239,96,...,7.8,0.445,0.516,89.0,74.17,90,0.565,1,0,93
15089,42022,1610612752,NYK,New York Knicks,42200206,2023-05-12,NYK @ MIA,L,240,92,...,13.6,0.451,0.541,89.0,74.17,88,0.435,1,0,93

In [233]:
home = []

for i in range(len(alldata)):
    if alldata['MATCHUP'][i][4] == "v":
        home.append(1)
    else:
        home.append(0)
        
alldata["HOME"] = home

win = []

for i in range(len(alldata)):
    if alldata['WL'][i] == "W":
        win.append(1)
    else:
        win.append(0)

alldata['WL'] = win

alldata["WIN_PERC"] = alldata_total['WL']

In [237]:
alldata

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,TS_PCT,PACE,PACE_PER40,POSS,PIE,PLAYOFF_IND,KEY_DNP,GAME_NUMBER,HOME,WIN_PERC
0,22017,1610612739,CLE,Cleveland Cavaliers,21700001,2017-10-17,CLE vs. BOS,1,239,102,...,0.543,98.5,82.08,98,0.491,0,0,1,1,1
1,22017,1610612738,BOS,Boston Celtics,21700001,2017-10-17,BOS @ CLE,0,241,99,...,0.500,98.5,82.08,99,0.509,0,0,1,0,0
2,22017,1610612744,GSW,Golden State Warriors,21700002,2017-10-17,GSW vs. HOU,0,241,121,...,0.678,101.0,84.17,101,0.515,0,0,1,1,0
3,22017,1610612745,HOU,Houston Rockets,21700002,2017-10-17,HOU @ GSW,1,239,122,...,0.579,101.0,84.17,101,0.485,0,0,1,0,1
4,22017,1610612749,MIL,Milwaukee Bucks,21700007,2017-10-18,MIL @ BOS,1,238,108,...,0.605,100.5,83.75,100,0.583,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15085,42022,1610612756,PHX,Phoenix Suns,42200226,2023-05-11,PHX vs. DEN,0,243,100,...,0.569,98.5,82.08,99,0.357,1,1,93,1,1
15086,42022,1610612747,LAL,Los Angeles Lakers,42200236,2023-05-12,LAL vs. GSW,1,240,122,...,0.653,95.5,79.58,95,0.667,1,0,94,1,0
15087,42022,1610612744,GSW,Golden State Warriors,42200236,2023-05-12,GSW @ LAL,0,241,101,...,0.463,95.5,79.58,96,0.333,1,0,95,0,1
15088,42022,1610612748,MIA,Miami Heat,42200206,2023-05-12,MIA vs. NYK,1,239,96,...,0.516,89.0,74.17,90,0.565,1,0,93,1,1
15089,42022,1610612752,NYK,New York Knicks,42200206,2023-05-12,NYK @ MIA,0,240,92,...,0.541,89.0,74.17,88,0.435,1,0,93,0,0

In [238]:
elo_hStats2 = alldata[alldata['HOME'] == 1] 
elo_aStats2 = alldata[alldata['HOME'] == 0] 

alldata2 = pd.merge(elo_hStats2, elo_aStats2, how="inner", left_on=['GAME_ID'], right_on = ['GAME_ID'])

alldata2 = alldata2.sort_values(by='GAME_DATE_x').reset_index(drop=True)

In [239]:
alldata2

,SEASON_ID_x,TEAM_ID_x,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE_x,MATCHUP_x,WL_x,MIN_x,PTS_x,...,TS_PCT_y,PACE_y,PACE_PER40_y,POSS_y,PIE_y,PLAYOFF_IND_y,KEY_DNP_y,GAME_NUMBER_y,HOME_y,WIN_PERC_y
0,22017,1610612739,CLE,Cleveland Cavaliers,21700001,2017-10-17,CLE vs. BOS,1,239,102,...,0.500,98.5,82.08,99,0.509,0,0,1,0,0
1,22017,1610612744,GSW,Golden State Warriors,21700002,2017-10-17,GSW vs. HOU,0,241,121,...,0.579,101.0,84.17,101,0.485,0,0,1,0,1
2,22017,1610612756,PHX,Phoenix Suns,21700012,2017-10-18,PHX vs. POR,0,241,76,...,0.606,100.5,83.75,101,0.836,0,0,1,0,0
3,22017,1610612754,IND,Indiana Pacers,21700004,2017-10-18,IND vs. BKN,1,240,140,...,0.606,116.0,96.67,115,0.438,0,0,1,0,1
4,22017,1610612753,ORL,Orlando Magic,21700005,2017-10-18,ORL vs. MIA,1,240,116,...,0.502,104.5,87.08,105,0.450,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7540,42022,1610612752,NYK,New York Knicks,42200205,2023-05-10,NYK vs. MIA,1,240,112,...,0.534,93.5,77.92,93,0.428,1,0,92,0,0
7541,42022,1610612755,PHI,Philadelphia 76ers,42200216,2023-05-11,PHI vs. BOS,0,242,86,...,0.559,96.0,80.00,96,0.551,1,1,94,0,1
7542,42022,1610612756,PHX,Phoenix Suns,42200226,2023-05-11,PHX vs. DEN,0,243,100,...,0.653,98.5,82.08,98,0.643,1,1,93,0,0
7543,42022,1610612747,LAL,Los Angeles Lakers,42200236,2023-05-12,LAL vs. GSW,1,240,122,...,0.463,95.5,79.58,96,0.333,1,0,95,0,1
7544,42022,1610612748,MIA,Miami Heat,42200206,2023-05-12,MIA vs. NYK,1,239,96,...,0.541,89.0,74.17,88,0.435,1,0,93,0,0

In [240]:
temp = []

for item in list(alldata2.columns):
    if item not in list(elo_reformat.columns):
        temp.append(item)

In [241]:
elo2 = alldata2.drop(columns=temp)

In [242]:
elo2

,SEASON_ID_x,TEAM_ID_x,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE_x,MATCHUP_x,WL_x,PTS_x,PLUS_MINUS_x,...,SEASON_ID_y,TEAM_ID_y,TEAM_ABBREVIATION_y,TEAM_NAME_y,GAME_DATE_y,MATCHUP_y,WL_y,PTS_y,PLUS_MINUS_y,HOME_y
0,22017,1610612739,CLE,Cleveland Cavaliers,21700001,2017-10-17,CLE vs. BOS,1,102,3.0,...,22017,1610612738,BOS,Boston Celtics,2017-10-17,BOS @ CLE,0,99,-3.0,0
1,22017,1610612744,GSW,Golden State Warriors,21700002,2017-10-17,GSW vs. HOU,0,121,-1.0,...,22017,1610612745,HOU,Houston Rockets,2017-10-17,HOU @ GSW,1,122,1.0,0
2,22017,1610612756,PHX,Phoenix Suns,21700012,2017-10-18,PHX vs. POR,0,76,-48.0,...,22017,1610612757,POR,Portland Trail Blazers,2017-10-18,POR @ PHX,1,124,48.0,0
3,22017,1610612754,IND,Indiana Pacers,21700004,2017-10-18,IND vs. BKN,1,140,9.0,...,22017,1610612751,BKN,Brooklyn Nets,2017-10-18,BKN @ IND,0,131,-9.0,0
4,22017,1610612753,ORL,Orlando Magic,21700005,2017-10-18,ORL vs. MIA,1,116,7.0,...,22017,1610612748,MIA,Miami Heat,2017-10-18,MIA @ ORL,0,109,-7.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7540,42022,1610612752,NYK,New York Knicks,42200205,2023-05-10,NYK vs. MIA,1,112,9.0,...,42022,1610612748,MIA,Miami Heat,2023-05-10,MIA @ NYK,0,103,-9.0,0
7541,42022,1610612755,PHI,Philadelphia 76ers,42200216,2023-05-11,PHI vs. BOS,0,86,-9.0,...,42022,1610612738,BOS,Boston Celtics,2023-05-11,BOS @ PHI,1,95,9.0,0
7542,42022,1610612756,PHX,Phoenix Suns,42200226,2023-05-11,PHX vs. DEN,0,100,-25.0,...,42022,1610612743,DEN,Denver Nuggets,2023-05-11,DEN @ PHX,1,125,25.0,0
7543,42022,1610612747,LAL,Los Angeles Lakers,42200236,2023-05-12,LAL vs. GSW,1,122,21.0,...,42022,1610612744,GSW,Golden State Warriors,2023-05-12,GSW @ LAL,0,101,-21.0,0
7544,42022,1610612748,MIA,Miami Heat,42200206,2023-05-12,MIA vs. NYK,1,96,4.0,...,42022,1610612752,NYK,New York Knicks,2023-05-12,NYK @ MIA,0,92,-4.0,0

In [243]:
elo_reformat = pd.concat([elo_reformat, elo2]).sort_values(by='GAME_DATE_x').reset_index(drop=True)

In [244]:
elo_reformat

,SEASON_ID_x,TEAM_ID_x,TEAM_ABBREVIATION_x,TEAM_NAME_x,GAME_ID,GAME_DATE_x,MATCHUP_x,WL_x,PTS_x,PLUS_MINUS_x,...,SEASON_ID_y,TEAM_ID_y,TEAM_ABBREVIATION_y,TEAM_NAME_y,GAME_DATE_y,MATCHUP_y,WL_y,PTS_y,PLUS_MINUS_y,HOME_y
0,21990,1610612746,LAC,Los Angeles Clippers,29000008,1990-11-02,LAC vs. SAC,1,90,10.0,...,21990,1610612758,SAC,Sacramento Kings,1990-11-02,SAC @ LAC,0,80,-10.0,0
1,21990,1610612737,ATL,Atlanta Hawks,29000010,1990-11-02,ATL vs. ORL,1,115,4.0,...,21990,1610612753,ORL,Orlando Magic,1990-11-02,ORL @ ATL,0,111,-4.0,0
2,21990,1610612738,BOS,Boston Celtics,29000012,1990-11-02,BOS vs. CLE,1,125,24.0,...,21990,1610612739,CLE,Cleveland Cavaliers,1990-11-02,CLE @ BOS,0,101,-24.0,0
3,21990,1610612765,DET,Detroit Pistons,29000005,1990-11-02,DET vs. MIL,1,115,11.0,...,21990,1610612749,MIL,Milwaukee Bucks,1990-11-02,MIL @ DET,0,104,-11.0,0
4,21990,1610612762,UTA,Utah Jazz,29000011,1990-11-02,UTH vs. PHX,0,96,-23.0,...,21990,1610612756,PHX,Phoenix Suns,1990-11-02,PHX @ UTH,1,119,23.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41182,42022,1610612752,NYK,New York Knicks,42200205,2023-05-10,NYK vs. MIA,1,112,9.0,...,42022,1610612748,MIA,Miami Heat,2023-05-10,MIA @ NYK,0,103,-9.0,0
41183,42022,1610612755,PHI,Philadelphia 76ers,42200216,2023-05-11,PHI vs. BOS,0,86,-9.0,...,42022,1610612738,BOS,Boston Celtics,2023-05-11,BOS @ PHI,1,95,9.0,0
41184,42022,1610612756,PHX,Phoenix Suns,42200226,2023-05-11,PHX vs. DEN,0,100,-25.0,...,42022,1610612743,DEN,Denver Nuggets,2023-05-11,DEN @ PHX,1,125,25.0,0
41185,42022,1610612747,LAL,Los Angeles Lakers,42200236,2023-05-12,LAL vs. GSW,1,122,21.0,...,42022,1610612744,GSW,Golden State Warriors,2023-05-12,GSW @ LAL,0,101,-21.0,0
41186,42022,1610612748,MIA,Miami Heat,42200206,2023-05-12,MIA vs. NYK,1,96,4.0,...,42022,1610612752,NYK,New York Knicks,2023-05-12,NYK @ MIA,0,92,-4.0,0

In [245]:
elo_reformat.to_csv('elo_reformat.csv')